name: Build & Release Signed APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Decode Keystore and Place it in root folder
      run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > release.keystore
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Find Unsigned APK
      id: find_apk
      run: |
        UNSIGNED_APK=$(find app/build/outputs/apk/release -name "*-unsigned.apk" | head -n 1)
        echo "unsigned_apk=$UNSIGNED_APK" >> $GITHUB_OUTPUT

    - name: Sign APK
      id: sign_apk
      uses: android-actions/sign-android-release@v1
      with:
        releaseDirectory: ${{ github.workspace }}
        signingKeyFile: release.keystore
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        
    - name: Rename APK
      run: |
        mv ${{ steps.sign_apk.outputs.signedReleaseFile }} RedBunnyNative-v${{ github.ref_name }}.apk

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: RedBunnyNative-v${{ github.ref_name }}.apk
        tag_name: ${{ github.ref_name }}
        body: "RedBunnyNative auto release for version ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
